### ISSUE TITLE
Execute another middleware after the mock middleware

### ISSUE THREAD

**Issue by aabeling** [aleksandryackovlev/openapi-mock-express-middleware#29]
Hi,

I would like to use another express middleware after the mock middleware has run. I tried something like this:
```
app.use(
  '/',
  function (req, res, next) {
      console.log("(1) handling request, new Date());
      next();
  },
  createMockMiddleware({ 
      spec: 'api.yaml'
    }),
  function (req, res, next) {
      // does not work
      console.log('(2) next middleware');
      next();
  }
);
```
The middleware (1) is executed and the mock middleware creates a response as expected but (2) is not executed.

These are my first steps with express so I am probably missing something. 
Is this possible at all with express and with openapi-mock-express-middleware?

Is it perhaps because `generateResponse` in `src/operations/operation.ts` already sends the response?

Best regards
Achim

**Comment by aabeling** [comment]
I managed to achieve what I wanted by overriding the `send` method of the response:
```
app.use(
  '/',
  function (req, res, next) {      
      var send = res.send;
      res.send = function(string) {
        // (3) do something with the response
        send.call(this, string);
      };
      next();
  },
  createMockMiddleware({ 
      spec: 'api.yaml'
    })
);
```
But that's really hacky.

**Comment by aleksandryackovlev** [comment]
Hi,
I think a better approach would be to code like this:
```
app.use(
  (req, res, next) => {
    console.log('before');
    next();
  },
  (req, res, next) => {
    createMockMiddleware({
      spec: 'api.yaml'
    })(req, res, next);

    next();
  },
  (req, res, next) => {
    console.log('after');
  },
);
```

One important thing to remember is that modifying the response or headers in the after middleware will cause an error.

**Comment by aleksandryackovlev** [comment]
Considering the fact that this discussion is not related to the package itself, but to the proper usage of express middleware, I'm closing this issue.
