### ISSUE TITLE
new feature for examples generations

### ISSUE THREAD

**Issue by jean13360** [aleksandryackovlev/openapi-mock-express-middleware#52]
I fork this project because i need some new features

-  During my API testing , i need to have a random response from the list of examples 

'200':
          description: Good
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Err0r1:
                    description: "Error1"
                    value:
                      detail: Error1
                Err0r2:
                    description: "Error2"
                    value:
                      detail: "Error2"

I change your implementation of method getResponseSchema because the  resultSchema.examples is not an array and the default generator not work

I do 
  if (!Array.isArray(examples)) {   
            let arrayOfExample = []         
            for (const key in examples) {
              arrayOfExample.push(examples[key].value)
            }
            resultSchema.examples = arrayOfExample;
            
            
Maybe you can add this type of feature ?  maybe you can also random the reponse 200/500 or 400?

 
I add too an new option to generate random value for items only described into the schema definition 

Thanks

**Comment by aleksandryackovlev** [comment]
A new option has been added. If you want to randomly generate responses from the `examples`, just add a new option `randomizeExamples` in the config:
```
createMockMiddleware({
  spec: '/the/path/to/your/spec/file',
  options: { randomizeExamples: true },
}); 
```

**Comment by jean13360** [comment]
Thx
